run:
  start: "2016-06-01"
  duration: "3d"
  dt_seconds: 1800
  snapshots_seconds: 1800
  backtrajectory: false
  time_loops: 0
  output:
    dir: "./OUT_DEV_LIST/"
    format: "parquet"
    mode: "steps"
    steps_layout: "time"
    steps_chunk_size: 86400

domain:
  type: "RegularLatLon"
  coords: {lon: "lon", lat: "lat", depth: "depth", time: "time"}
  velocity:
    u: {var: "ugo"}
    v: {var: "vgo"}
    w: {var: null}
  files:
    mode: "list"
    list:
      - "examples/dataset_day01.nc"
      - "examples/dataset_day02.nc"
      - "examples/dataset_day03.nc"

starts:
  file: "examples/starts_dummy.dat"
  format: "pairs_xyz_age#col8_preserve"

output:
  dir: "./OUT_DEV_LIST/"
  format: "parquet"
  mode: "steps"
  steps_layout: "time"

mask:
  enabled: true      # attiva la maschera
  threshold: 0.5     # se sample_mask < threshold â†’ particella uccisa
  speed_min: 0.0     # speed>speed_min & finite = mare (per tutte le depth)
