run:
  start: "2016-06-01"
  duration: "3d"
  dt_seconds: 60
  snapshots_seconds: 86400
  backtrajectory: false
  time_loops: 0         # 0 = niente loop; >0 = ripeti N cicli temporali dei file
  output:
    dir: "./OUT_DEV_LIST/"
    format: "parquet"
    mode: "steps"
    steps_layout: "time"
    steps_chunk_size: 86400  # chunk di 1 giorno in questo test

domain:
  type: "RegularLatLon"
  coords: {lon: "lon", lat: "lat", depth: "depth", time: "time"}
  velocity:
    u: {var: "ugo"}
    v: {var: "vgo"}
    w: {var: null}
  files:
    mode: "list"
    list:
      - "examples/dataset_day01.nc"
      - "examples/dataset_day02.nc"
      - "examples/dataset_day03.nc"

starts:
  file: "examples/starts_dummy.dat"
  format: "pairs_xyz_age#col8_preserve"

output:
  dir: "./OUT_DEV_LIST/"
  format: "parquet"
  mode: "steps"            # "steps" | "snaps" | "steps_and_snaps"
  steps_layout: "time"     # (per ora fisso "time")
  steps_chunk_size: 1000   # n. step per file (per-rank)